[sklearn_conf]

SVC = [
    { C = [1, 10, 100, 1000], kernel = ["linear"]},
    { C = [1, 10, 100, 1000], gamma = [0.001, 0.0001], kernel = ["rbf"]}
  ]

RandomForestClassifier = [
    { n_estimators = [ 100, 200, 400 ], max_depth = [3, 10, 100] }
]

[optuna_conf]

[mlflow_conf]
